title: "CloudEnv Docs"
remote_theme: pmarsceill/just-the-docs

footer_content: "Copyright &copy; 2021 CloudEnv. Distributed by an <a href=\"https://github.com/cloudenvhq/docs/blob/main/LICENSE\">MIT license.</a>"

ga_tracking: UA-48621206-9
